gui:
  border: 'rounded'
  theme:
    activeBorderColor:
      - '#22e8df'
    inactiveBorderColor:
      - '#545c7e'
    searchingActiveBorderColor:
      - '#dc396a'
    optionsTextColor:
      - '#22e8df'
    selectedLineBgColor:
      - '#292E42'
    inactiveViewSelectedLineBgColor:
      - '#292E42'
    unstagedChangesColor:
      - '#dc396a'
    cherryPickedCommitBgColor:
      - '#22e8df'
    cherryPickedCommitFgColor:
      - '#24283B'
    markedBaseCommitBgColor:
      - '#e6c62f'
    markedBaseCommitFgColor:
      - '#24283B'
