unbind C-b
set -g prefix C-s
bind C-s send-prefix

set -g base-index 1
setw -g pane-base-index 1

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind Left       previous-window
bind h          previous-window
bind Right          next-window
bind l          next-window

set -g mouse on

setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi y send -X copy-selection-and-cancel

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g allow-rename off

# Status bar customization
set-option -g status-position top
set -g status-interval 5

set -g @icon-app ''
set -g @icon-left ''
set -g @icon-right ''
set -g @icon-separator ''
setw -g window-status-separator ''

set -g status-style "bg=#000c16,fg=#143652"
set -g mode-style 'fg=#bcf3ff,bg=#143652'

set -g status-left-length 32
set -g status-left "\
#[bg=#{?client_prefix,#dc396a,#22e8df}]\
#[fg=#{?client_prefix,#ffffff,#001628}] #{@icon-app} \
#[bg=#{?client_prefix,#dc396a,#143652}]#[fg=#{?client_prefix,#dc396a,#22e8df}]#{@icon-right} \
#[fg=#{?client_prefix,#ffffff,#22e8df}]#S \
#[fg=#{?client_prefix,#dc396a,#143652}]#[bg=#000c16]#{@icon-right}\
#[default]"

set -g pane-border-style "fg=#495162"
set -g pane-active-border-style "fg=#22e8df"
setw -g window-status-format "#[fg=#44475a] #I #[fg=#6a7a7a]#W #[fg=#143652]#{@icon-separator}"
setw -g window-status-current-format "#[fg=#dc386a] #I #[fg=#e6c62f]#W #[fg=#143652]#{@icon-separator}"

set -g status-right "\
#[bg=#000c16]#[fg=#{?client_prefix,#dc396a,#143652}] \
#{@icon-left}\
#[bg=#{?client_prefix,#dc396a,#143652}]#[fg=#{?client_prefix,#ffffff,#c0caf5}] \
#(date '+  %%b %%d   %%H:%%M') "

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run '~/.tmux/plugins/tpm/tpm'
